-- AUTO-GENERATED by scripts/build-subject-grade-catalog-seed.mjs — do not edit by hand
-- Generated: 2026-07-11T18:21:55.434Z

insert into public.subject_permission_catalog (subject_key, display_name_he, sort_order, is_active)
values
  ('math', 'מתמטיקה', 1, true),
  ('geometry', 'גאומטריה', 2, true),
  ('hebrew', 'עברית', 3, true),
  ('english', 'אנגלית', 4, true),
  ('science', 'מדעים', 5, true),
  ('history', 'היסטוריה', 6, true),
  ('moledet', 'מולדת', 7, true),
  ('geography', 'גאוגרפיה', 8, true)
on conflict (subject_key) do update set
  display_name_he = excluded.display_name_he,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

insert into public.subject_grade_default_catalog (grade_key, subject_key, is_grade_suitable, is_enabled_by_default)
values
  ('g1', 'math', true, true),
  ('g1', 'geometry', true, true),
  ('g1', 'hebrew', true, true),
  ('g1', 'english', true, true),
  ('g1', 'science', true, true),
  ('g1', 'history', false, false),
  ('g1', 'moledet', false, false),
  ('g1', 'geography', false, false),
  ('g2', 'math', true, true),
  ('g2', 'geometry', true, true),
  ('g2', 'hebrew', true, true),
  ('g2', 'english', true, true),
  ('g2', 'science', true, true),
  ('g2', 'history', false, false),
  ('g2', 'moledet', true, true),
  ('g2', 'geography', false, false),
  ('g3', 'math', true, true),
  ('g3', 'geometry', true, true),
  ('g3', 'hebrew', true, true),
  ('g3', 'english', true, true),
  ('g3', 'science', true, true),
  ('g3', 'history', false, false),
  ('g3', 'moledet', true, true),
  ('g3', 'geography', false, false),
  ('g4', 'math', true, true),
  ('g4', 'geometry', true, true),
  ('g4', 'hebrew', true, true),
  ('g4', 'english', true, true),
  ('g4', 'science', true, true),
  ('g4', 'history', false, false),
  ('g4', 'moledet', true, true),
  ('g4', 'geography', false, false),
  ('g5', 'math', true, true),
  ('g5', 'geometry', true, true),
  ('g5', 'hebrew', true, true),
  ('g5', 'english', true, true),
  ('g5', 'science', true, true),
  ('g5', 'history', false, false),
  ('g5', 'moledet', false, false),
  ('g5', 'geography', true, true),
  ('g6', 'math', true, true),
  ('g6', 'geometry', true, true),
  ('g6', 'hebrew', true, true),
  ('g6', 'english', true, true),
  ('g6', 'science', true, true),
  ('g6', 'history', true, true),
  ('g6', 'moledet', false, false),
  ('g6', 'geography', true, true)
on conflict (grade_key, subject_key) do update set
  is_grade_suitable = excluded.is_grade_suitable,
  is_enabled_by_default = excluded.is_enabled_by_default;
