/** @type {import("./taxonomy-types.js").TaxonomyRow[]} */
export const HEBREW_TAXONOMY_ROWS = [
  {
    id: "H-01",
    subjectId: "hebrew",
    domainHe: "אוצר",
    topicHe: "הקשר",
    subskillHe: "נרדפת",
    patternHe: "מילה קרובה לא נכונה",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בהקשרים שונים"],
    counterEvidenceHe: "נכון אחרי הסבר הפרש",
    countsWhenHe: "הקשר מובחן",
    doesNotCountWhenHe: "רק מסיח חלש מאוד",
    rootsHe: ["אוצר דק"],
    competitorsHe: ["קריאה"],
    doNotConcludeHe: ["עברית חלשה"],
    probeHe: "זוג משפטים מקבילים",
    interventionHe: "זוג מילים + החלפה",
    escalationHe: "קושי בכל תחום",
  },
  {
    id: "H-02",
    subjectId: "hebrew",
    domainHe: "דקדוק",
    topicHe: "התאמה",
    subskillHe: "מגדר/מספר",
    patternHe: "כינוי/שם עצם שגוי",
    minWrong: 4,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["אותה טעות", "נושא מודגש"],
    counterEvidenceHe: "נכון בכתיבה איטית מאוד",
    countsWhenHe: "נושא מפורש",
    doesNotCountWhenHe: "הקלדה מהירה בלבד",
    rootsHe: ["כללי התאמה"],
    competitorsHe: ["רשלנות"],
    doNotConcludeHe: ["דיסלקציה"],
    probeHe: "נושא מודגש",
    interventionHe: "טבלת התאמה",
    escalationHe: "דיווח חוצהמקצועות",
  },
  {
    id: "H-03",
    subjectId: "hebrew",
    domainHe: "כתיב",
    topicHe: "דפוס",
    subskillHe: "משפחת כתיב",
    patternHe: "אותה משפחה שגויה",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["אותו שורש במילים שונות"],
    counterEvidenceHe: "נכון עם מתקן הקלדה",
    countsWhenHe: "כתב יד או הקלדה עקבית",
    doesNotCountWhenHe: "בלי תיקון כשמטרה כתיב",
    rootsHe: ["כלל כתיב"],
    competitorsHe: ["הקלדה"],
    doNotConcludeHe: ["אין כתיב"],
    probeHe: "כתב יד מול הקלדה",
    interventionHe: "כלל משפחה + 5 מילים",
    escalationHe: "אין שיפור",
  },
  {
    id: "H-04",
    subjectId: "hebrew",
    domainHe: "הנקרא",
    topicHe: "עובדה",
    subskillHe: "חיפוש",
    patternHe: "טעות כשעובדה לא בסדר קריאה",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בשני טקסטים"],
    counterEvidenceHe: "נכון עם כותרות פנימיות",
    countsWhenHe: "פסקאות ממוספרות",
    doesNotCountWhenHe: "טקסט מעל הרמה",
    rootsHe: ["אסטרטגיית חיפוש"],
    competitorsHe: ["עייפות"],
    doNotConcludeHe: ["אין הבנה"],
    probeHe: "עם/בלי כותרות",
    interventionHe: "חיפוש עם סימון",
    escalationHe: "גם בטקסט קצר מאוד",
  },
  {
    id: "H-05",
    subjectId: "hebrew",
    domainHe: "ניקוד",
    topicHe: "הקשר",
    subskillHe: "הומופון",
    patternHe: "טעות רק בהומופון",
    minWrong: 4,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["נכון בלי הומופון"],
    counterEvidenceHe: "נכון עם רמז משמעותי קצר",
    countsWhenHe: "הומופון מבחינה",
    doesNotCountWhenHe: "בלי הומופון",
    rootsHe: ["כלל הקשר"],
    competitorsHe: ["אוצר"],
    doNotConcludeHe: ["אין עברית"],
    probeHe: "זוג משפטים מינימלי",
    interventionHe: "כלל בזוגות",
    escalationHe: "כישלון בלא הומופון",
  },
  {
    id: "H-06",
    subjectId: "hebrew",
    domainHe: "תחביר",
    topicHe: "משפט",
    subskillHe: "סדר שאלה",
    patternHe: "סדר מילים שגוי",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["חוזר ב 3 סוגי שאלות"],
    counterEvidenceHe: "נכון בתבנית מודפסת",
    countsWhenHe: "תבנית נלמדת",
    doesNotCountWhenHe: "לפני לימוד סדר",
    rootsHe: ["תחביר"],
    competitorsHe: ["אוצר"],
    doNotConcludeHe: ["אין דיבור"],
    probeHe: "השלמת מילות שאלה",
    interventionHe: "תבניות מיניות",
    escalationHe: "אין שיפור",
  },
  {
    id: "H-07",
    subjectId: "hebrew",
    domainHe: "כתיבה",
    topicHe: "ניסוח",
    subskillHe: "חיבור משפטים",
    patternHe: "משפטים לא מחוברים",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["רצף שבור חוזר"],
    counterEvidenceHe: "נכון במשפט בודד",
    countsWhenHe: "מילות קישור זמינות",
    doesNotCountWhenHe: "בלי מילות קישור בחומר",
    rootsHe: ["סינטקס"],
    competitorsHe: ["רעיונות"],
    doNotConcludeHe: ["אין מחשבה"],
    probeHe: "שני משפטים עם קישור חובה",
    interventionHe: "מילות קישור",
    escalationHe: "קושי במשפט אחד",
  },
  {
    id: "H-08",
    subjectId: "hebrew",
    domainHe: "שפה",
    topicHe: "ניסוח",
    subskillHe: "פורמליות",
    patternHe: "רגיסטר שגוי חוזר",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בהקשרים פורמליים"],
    counterEvidenceHe: "נכון ברשימה סגורה",
    countsWhenHe: "נלמד במפורש",
    doesNotCountWhenHe: "לא נלמד הרשמה",
    rootsHe: ["פרגמטיקה"],
    competitorsHe: ["אוצר"],
    doNotConcludeHe: ["בעיית התנהגות"],
    probeHe: "זוג פורמלי",
    interventionHe: "כלל מיני + דוגמאות",
    escalationHe: "מורה חברתי",
  },
];
