/** @type {import("./taxonomy-types.js").TaxonomyRow[]} */
export const HISTORY_TAXONOMY_ROWS = [
  {
    id: "H-01",
    subjectId: "history",
    domainHe: "מושג",
    topicHe: "יסודות",
    subskillHe: "מושגים היסטוריים",
    patternHe: "בלבול מושגי",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בשני מושגים דומים"],
    counterEvidenceHe: "נכון אחרי הגדרה מודרכת",
    countsWhenHe: "מושג מוגדר בשאלה",
    doesNotCountWhenHe: "מסיחים הומופוניים בלבד",
    rootsHe: ["בלבול מושגי"],
    competitorsHe: ["זיכרון שמות"],
    doNotConcludeHe: ["אין היסטוריה"],
    probeHe: "הפרדה בין מושגים קרובים",
    interventionHe: "כרטיסיות מושג–הגדרה",
    escalationHe: "אין שיפור",
  },
  {
    id: "H-02",
    subjectId: "history",
    domainHe: "ציר זמן",
    topicHe: "רצף",
    subskillHe: "ציר זמן ורצף אירועים",
    patternHe: "סדר אירועים שגוי",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בשני צירי זמן"],
    counterEvidenceHe: "נכון עם תאריכים מודפסים",
    countsWhenHe: "ציר זמן זמין",
    doesNotCountWhenHe: "יותר מדי נקודות לפני שלב",
    rootsHe: ["ציר זמן"],
    competitorsHe: ["שמות דומים"],
    doNotConcludeHe: ["אין הבנה"],
    probeHe: "עם/בלי תאריכים",
    interventionHe: "ציר פיזי + כרטיסיות",
    escalationHe: "אין שיפור",
  },
  {
    id: "H-03",
    subjectId: "history",
    domainHe: "הסקה",
    topicHe: "סיבה ותוצאה",
    subskillHe: "סיבה ותוצאה",
    patternHe: "סיבה שגויה חוזרת",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות כשיש טקסט הסבר"],
    counterEvidenceHe: "נכון ברשימה סגורה",
    countsWhenHe: "טקסט הסבר קצר",
    doesNotCountWhenHe: "רק שמות דמויות",
    rootsHe: ["הסקת סיבה"],
    competitorsHe: ["זיכרון"],
    doNotConcludeHe: ["דעות קדומות"],
    probeHe: "שני הסברים מנוגדים",
    interventionHe: "שאלת מאין ידוע",
    escalationHe: "מורה חברתי",
  },
  {
    id: "H-04",
    subjectId: "history",
    domainHe: "השוואה",
    topicHe: "דמיון והבדל",
    subskillHe: "השוואה",
    patternHe: "השוואה חלקית שגויה",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בשני זוגות"],
    counterEvidenceHe: "נכון עם טבלת השוואה",
    countsWhenHe: "טבלה או שני עמודות",
    doesNotCountWhenHe: "בלי קריטריון השוואה",
    rootsHe: ["קריטריון השוואה"],
    competitorsHe: ["זיכרון"],
    doNotConcludeHe: ["אין הבנה"],
    probeHe: "עם/בלי קריטריון מפורש",
    interventionHe: "טבלת דמיון/הבדל",
    escalationHe: "אין שיפור",
  },
  {
    id: "H-05",
    subjectId: "history",
    domainHe: "דמויות",
    topicHe: "תפקיד",
    subskillHe: "דמויות ותפקידן",
    patternHe: "בלבול תפקידים",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות חוזרת בין דמויות"],
    counterEvidenceHe: "נכון ברשימה",
    countsWhenHe: "רשימת דמויות נלמדת",
    doesNotCountWhenHe: "דמויות שלא נלמדו",
    rootsHe: ["מבנה ידע"],
    competitorsHe: ["שמות"],
    doNotConcludeHe: ["בעיה חברתית"],
    probeHe: "התאמת דמות לתפקיד",
    interventionHe: "טבלת דמות–תפקיד",
    escalationHe: "אין שיפור",
  },
  {
    id: "H-06",
    subjectId: "history",
    domainHe: "שלטון",
    topicHe: "מוסדות",
    subskillHe: "שלטון ומוסדות",
    patternHe: "בלבול מוסדות",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות חוזרת בין מוסדות"],
    counterEvidenceHe: "נכון ברשימה",
    countsWhenHe: "רשימה נלמדת",
    doesNotCountWhenHe: "מוסדות שלא נלמדו",
    rootsHe: ["מבנה שלטון"],
    competitorsHe: ["שמות"],
    doNotConcludeHe: ["ערכים"],
    probeHe: "התאמת מוסד לתפקיד",
    interventionHe: "טבלת מוסד–תפקיד",
    escalationHe: "אין שיפור",
  },
  {
    id: "H-07",
    subjectId: "history",
    domainHe: "תרבות",
    topicHe: "מורשת",
    subskillHe: "תרבות ומורשת",
    patternHe: "בלבול השפעה",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות כשיש דוגמה"],
    counterEvidenceHe: "נכון עם דוגמה מודרכת",
    countsWhenHe: "דוגמה מהשיעור",
    doesNotCountWhenHe: "בלי לימוד תרבות",
    rootsHe: ["מורשת תרבותית"],
    competitorsHe: ["זיכרון"],
    doNotConcludeHe: ["אין הבנה"],
    probeHe: "עם/בלי דוגמה",
    interventionHe: "קישור תרבות–השפעה",
    escalationHe: "אין שיפור",
  },
  {
    id: "H-08",
    subjectId: "history",
    domainHe: "מקור",
    topicHe: "ראיות",
    subskillHe: "הבנת מקור היסטורי פשוט",
    patternHe: "טענה לא מבוססת",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["חוזר כשיש מקור מפורש"],
    counterEvidenceHe: "נכון כשמבקשים מקור",
    countsWhenHe: "מקורות מסומנים",
    doesNotCountWhenHe: "מסיח פרסומי",
    rootsHe: ["ביקורתיות"],
    competitorsHe: ["קריאה"],
    doNotConcludeHe: ["ערכים אישיים"],
    probeHe: "עם/בלי מקור",
    interventionHe: "שאלת מאין ידוע",
    escalationHe: "מורה חברתי",
  },
  {
    id: "H-09",
    subjectId: "history",
    domainHe: "קשר",
    topicHe: "עבר והווה",
    subskillHe: "קשר בין עבר להווה",
    patternHe: "קשר שגוי חוזר",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בשני קישורים"],
    counterEvidenceHe: "נכון עם שאלת השוואה",
    countsWhenHe: "שאלה מקשרת עבר–הווה",
    doesNotCountWhenHe: "בלי לימוד קשר",
    rootsHe: ["הקשר היסטורי"],
    competitorsHe: ["דעה"],
    doNotConcludeHe: ["ערכים"],
    probeHe: "עם/בלי הנחיה מקשרת",
    interventionHe: "שאלת מה נשאר מהעבר",
    escalationHe: "אין שיפור",
  },
];
