/**
 * טקסונומיית מתמטיקה — מימוש מסמך stage1-scientific-blueprint-source-of-truth §5.1
 * שדות מכונות: ספי חזרתיות מפורשים לפי המסמך.
 * @typedef {import("./taxonomy-types.js").TaxonomyRow} TaxonomyRow
 */

/** @type {TaxonomyRow[]} */
export const MATH_TAXONOMY_ROWS = [
  {
    id: "M-01",
    subjectId: "math",
    domainHe: "מספר",
    topicHe: "מבנה",
    subskillHe: "פירוק 10+1",
    patternHe: "טעויות בהמרת ייצוג",
    minWrong: 3,
    minDistinctPatternFamilies: 2,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות זהות בשני ייצוגים", "איטיות לפני תשובה"],
    counterEvidenceHe: "הצלחה עם ייצוג מוצג בלי הסבר ארוך",
    countsWhenHe: "משימות שקולות; בלי רמז שמציג פתרון מלא",
    doesNotCountWhenHe: "רמז מלא; משימה בודדת",
    rootsHe: ["פער ייצוג"],
    competitorsHe: ["קריאה"],
    doNotConcludeHe: ["אין חשבון"],
    probeHe: "שני ייצוגים לאותו מספר",
    interventionHe: "מניפולציה + מעבר הדרגתי לסמל",
    escalationHe: "כישלון בכל ייצוג",
  },
  {
    id: "M-02",
    subjectId: "math",
    domainHe: "פעולות",
    topicHe: "חיבור",
    subskillHe: "נשיאה",
    patternHe: "שגיאה בעמודת עשרות",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 2,
    observableMarkersHe: ["אותו סוג טעות בגדלים שונים"],
    counterEvidenceHe: "נכון כשאין נשיאה",
    countsWhenHe: "ספרות כתובות",
    doesNotCountWhenHe: "רק קיצון מספרים בלי בסיס נשיאה",
    rootsHe: ["אלגוריתם נשיאה"],
    competitorsHe: ["רשלנות"],
    doNotConcludeHe: ["חוסר תבונה"],
    probeHe: "חיבור עם/בלי נשיאה",
    interventionHe: "נשיאה עם ביניים",
    escalationHe: "תלות בביניים ללא קידום",
  },
  {
    id: "M-03",
    subjectId: "math",
    domainHe: "פעולות",
    topicHe: "כפל",
    subskillHe: "עובדת כפל",
    patternHe: "אותם זוגות שגויים",
    minWrong: 4,
    minDistinctPatternFamilies: 2,
    minDistinctDays: 0,
    observableMarkersHe: ["רשימת זוגות חופפת"],
    counterEvidenceHe: "זוגות אחרים נכונים באותו מפגש",
    countsWhenHe: "תרגול רגיל; לא רק מבחן מהירות",
    doesNotCountWhenHe: "מבחן מהירות בלבד",
    rootsHe: ["פער עובדה"],
    competitorsHe: ["לחץ זמן"],
    doNotConcludeHe: ["אין כפל"],
    probeHe: "זמן כפול לאותו סט",
    interventionHe: "תרגול ממוקד זוג",
    escalationHe: "כישלון בכל זוג גם לאט",
  },
  {
    id: "M-04",
    subjectId: "math",
    domainHe: "שברים",
    topicHe: "ייצוג",
    subskillHe: "חלק כלל",
    patternHe: "השוואה לפי מונה בלבד",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות כשהשרטוט מלא"],
    counterEvidenceHe: "נכון כשמכנים שווים במקרה",
    countsWhenHe: "שרטוט/פס זמין",
    doesNotCountWhenHe: "מילולי בלי ייצוג שלא נלמד",
    rootsHe: ["פער מושג שבר"],
    competitorsHe: ["רשלנות"],
    doNotConcludeHe: ["אין שברים"],
    probeHe: "עם/בלי שרטוט",
    interventionHe: "חלק כלל קונקרטי",
    escalationHe: "אין שיפור בכל ייצוג",
  },
  {
    id: "M-05",
    subjectId: "math",
    domainHe: "שברים",
    topicHe: "חיבור",
    subskillHe: "המראה",
    patternHe: "טעות באותה שלב",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בהכפלה/הרחבה חוזרת"],
    counterEvidenceHe: "נכון במכנים זהים",
    countsWhenHe: "מכנים קטנים בטווח הלימוד",
    doesNotCountWhenHe: "מכנים גדולים לפני כפל בסיסי",
    rootsHe: ["אלגוריתם המראה"],
    competitorsHe: ["כפל חלש"],
    doNotConcludeHe: ["אין שברים"],
    probeHe: "המראה 2,3,4",
    interventionHe: "שלבים כתובים + דוגמה מקבילה",
    escalationHe: "כישלון בכפל בסיסי",
  },
  {
    id: "M-06",
    subjectId: "math",
    domainHe: "עשרוניים",
    topicHe: "מקום",
    subskillHe: "עיגול/השוואה",
    patternHe: "טעות כיוון עיגול",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות חוזרת באותו כלל"],
    counterEvidenceHe: "נכון בטבלת עמדות",
    countsWhenHe: "מספרים לא עגולים",
    doesNotCountWhenHe: "רק עגולים במשימה",
    rootsHe: ["פער מיקום ספרה"],
    competitorsHe: ["קריאה"],
    doNotConcludeHe: ["אין עשרוניות"],
    probeHe: "עם/בלי טבלת עמדות",
    interventionHe: "צביעת עמדות",
    escalationHe: "כישלון גם בטבלה",
  },
  {
    id: "M-07",
    subjectId: "math",
    domainHe: "מילולי",
    topicHe: "ניסוח",
    subskillHe: "יחידות",
    patternHe: "מספר נכון + יחידה שגויה",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["חזרה על יחידה לא מתאימה"],
    counterEvidenceHe: "נכון כשמבקשים רק מספר",
    countsWhenHe: "יחידה מפורשת בטקסט",
    doesNotCountWhenHe: "שאלה בלי יחידה במקור",
    rootsHe: ["קריאת שאלה"],
    competitorsHe: ["חישוב"],
    doNotConcludeHe: ["אין הבנה"],
    probeHe: "עם/בלי שדה יחידה",
    interventionHe: "מספר + שורת יחידה",
    escalationHe: "קושי גם בלי יחידה",
  },
  {
    id: "M-08",
    subjectId: "math",
    domainHe: "מילולי",
    topicHe: "מודל",
    subskillHe: "רבשלבי",
    patternHe: "כישלון רק באיחוד",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["שגיאה באותו שלב אחרון"],
    counterEvidenceHe: "הצלחה עם שלבים מודפסים",
    countsWhenHe: "שלבים ממוספרים",
    doesNotCountWhenHe: "גרסה בלי שלבים כשלא נלמד",
    rootsHe: ["עומס זיכרון עבודה"],
    competitorsHe: ["פער חישוב"],
    doNotConcludeHe: ["אין מילולי"],
    probeHe: "עם תבנית שלבים",
    interventionHe: "שלבים + בדיקה לאחור",
    escalationHe: "כישלון גם בחד שלבי",
  },
  {
    id: "M-09",
    subjectId: "math",
    domainHe: "פעולות",
    topicHe: "חיסור",
    subskillHe: "השלמה לעשר",
    patternHe: "כיוון הפוך / הוספה במקום חיסור",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות כיוון חוזרת"],
    counterEvidenceHe: "נכון על ציר מספרים",
    countsWhenHe: "ציר או קו זמין",
    doesNotCountWhenHe: "מילולי ארוך בלי ייצוג כשלא נלמד",
    rootsHe: ["מושג חיסור"],
    competitorsHe: ["קריאה"],
    doNotConcludeHe: ["בעיה חשבונית כללית"],
    probeHe: "ציר + סימבולי",
    interventionHe: "ציר + מרחק",
    escalationHe: "אין שיפור בשני ייצוגים",
  },
  {
    id: "M-10",
    subjectId: "math",
    domainHe: "כפל/חילוק",
    topicHe: "יחס",
    subskillHe: "הופכיות",
    patternHe: "בחירת כפל לא מתאים לחילוק",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות כשאין משפט כפל"],
    counterEvidenceHe: "נכון כשמשפט כפל מוצג",
    countsWhenHe: "מספרים קטנים",
    doesNotCountWhenHe: "מספרים גדולים לפני שליטה בכפל",
    rootsHe: ["יחס הופכי"],
    competitorsHe: ["רשלנות"],
    doNotConcludeHe: ["אין חילוק"],
    probeHe: "עם/בלי משפט כפל",
    interventionHe: "קישור כפלחילוק",
    escalationHe: "כישלון תמיד",
  },
];
