/** @type {import("./taxonomy-types.js").TaxonomyRow[]} */
export const ENGLISH_TAXONOMY_ROWS = [
  {
    id: "E-01",
    subjectId: "english",
    domainHe: "אוצר",
    topicHe: "הקשר",
    subskillHe: "collocation",
    patternHe: "תרגום מילולי שגוי",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["אותו שורש במשפטים שונים"],
    counterEvidenceHe: "נכון אחרי שני דוגמאות",
    countsWhenHe: "משפטים ברורים",
    doesNotCountWhenHe: "מסיח false friend בלבד",
    rootsHe: ["false friend"],
    competitorsHe: ["דקדוק"],
    doNotConcludeHe: ["אין אנגלית"],
    probeHe: "משפטים מקבילים",
    interventionHe: "כרטיסיות משפט",
    escalationHe: "קושי בכל נושא",
  },
  {
    id: "E-02",
    subjectId: "english",
    domainHe: "דקדוק",
    topicHe: "זמנים",
    subskillHe: "סממן זמן",
    patternHe: "past/present",
    minWrong: 4,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות כשאתמול/עכשיו מפורש"],
    counterEvidenceHe: "נכון עם טבלת סממנים",
    countsWhenHe: "סממן מודגש",
    doesNotCountWhenHe: "זמן מעורבב בלי לימוד",
    rootsHe: ["מפת זמנים"],
    competitorsHe: ["אוצר"],
    doNotConcludeHe: ["אין דקדוק"],
    probeHe: "משפטים זהים, סממן שונה",
    interventionHe: "טבלת סממנים",
    escalationHe: "אין שיפור",
  },
  {
    id: "E-03",
    subjectId: "english",
    domainHe: "קריאה",
    topicHe: "פריסה",
    subskillHe: "מעקב שורות",
    patternHe: "טעות בדועמודי",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות רק בדועמודי"],
    counterEvidenceHe: "נכון בטור אחד רחב",
    countsWhenHe: "גופן קריא",
    doesNotCountWhenHe: "גופן זעיר בלי שלב",
    rootsHe: ["מעקב שורות"],
    competitorsHe: ["אוצר"],
    doNotConcludeHe: ["אין קריאה"],
    probeHe: "גופן גדול מול קטן",
    interventionHe: "מספר שורה / אצבע",
    escalationHe: "דיווח ראייה",
  },
  {
    id: "E-04",
    subjectId: "english",
    domainHe: "דקדוק",
    topicHe: "התאמה",
    subskillHe: "כינוי לנושא",
    patternHe: "he/she/it",
    minWrong: 4,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות", "נושא מודגש"],
    counterEvidenceHe: "נכון איטי מאוד",
    countsWhenHe: "נושא מפורש",
    doesNotCountWhenHe: "רק הקלדה מהירה",
    rootsHe: ["התאמה תחבירית"],
    competitorsHe: ["מהירות"],
    doNotConcludeHe: ["אין ידע"],
    probeHe: "שרשרת עם נושא",
    interventionHe: "טבלת נושא–כינוי",
    escalationHe: "כישלון תמיד",
  },
  {
    id: "E-05",
    subjectId: "english",
    domainHe: "אוצר",
    topicHe: "שימוש",
    subskillHe: "preposition",
    patternHe: "אותה יחס שגויה",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות עם פעלים שונים"],
    counterEvidenceHe: "נכון ברשימה סגורה",
    countsWhenHe: "יחסים נלמדים",
    doesNotCountWhenHe: "פעלים שלא נלמדו",
    rootsHe: ["אוצר ספציפי"],
    competitorsHe: ["דקדוק כללי"],
    doNotConcludeHe: ["אין שפה"],
    probeHe: "אותו פועל, שני יחסים",
    interventionHe: "זוגות מיניים",
    escalationHe: "אין שיפור",
  },
  {
    id: "E-06",
    subjectId: "english",
    domainHe: "קריאה",
    topicHe: "הבנה",
    subskillHe: "inference",
    patternHe: "עובדה במקום הסקה",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות רק ב inference"],
    counterEvidenceHe: "נכון בעובדה מפורשת",
    countsWhenHe: "סוג שאלה מסומן",
    doesNotCountWhenHe: "לפני לימוד inference",
    rootsHe: ["אסטרטגיה"],
    competitorsHe: ["אוצר"],
    doNotConcludeHe: ["אין חשיבה"],
    probeHe: "עובדה מול inference",
    interventionHe: "מילות סימן להסקה",
    escalationHe: "כישלון גם בעובדה",
  },
  {
    id: "E-07",
    subjectId: "english",
    domainHe: "כתיבה",
    topicHe: "איות",
    subskillHe: "תבניות שקטות",
    patternHe: "שגיאות חוזרות",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["אותה תבנית"],
    counterEvidenceHe: "נכון בהקראה איטית",
    countsWhenHe: "מילים שנלמדו",
    doesNotCountWhenHe: "לפני כלל",
    rootsHe: ["פונולוגיה"],
    competitorsHe: ["הקלדה"],
    doNotConcludeHe: ["לקות"],
    probeHe: "כתב יד מבוקר",
    interventionHe: "כלל איות מיני",
    escalationHe: "דיווח מקצועי",
  },
  {
    id: "E-08",
    subjectId: "english",
    domainHe: "האזנה",
    topicHe: "פונמי",
    subskillHe: "minimal pairs",
    patternHe: "בלבול צמד צלילים",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות באותו זוג"],
    counterEvidenceHe: "נכון בהאזנה איטית כפולה",
    countsWhenHe: "הקלטה ברורה",
    doesNotCountWhenHe: "רעש ידוע",
    rootsHe: ["פונמיקה"],
    competitorsHe: ["רעש"],
    doNotConcludeHe: ["לקות שמיעה"],
    probeHe: "אותו זוג במילים שונות",
    interventionHe: "תרגול זוגי",
    escalationHe: "דיווח שמיעה",
  },
];
