/** @type {import("./taxonomy-types.js").TaxonomyRow[]} */
export const MOLEDET_TAXONOMY_ROWS = [
  {
    id: "MG-01",
    subjectId: "moledet-geography",
    domainHe: "גאוגרפיה",
    topicHe: "מפה",
    subskillHe: "סולם",
    patternHe: "מרחקים יחסיים שגויים",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בשני קטעים"],
    counterEvidenceHe: "נכון עם סרגל מודרך",
    countsWhenHe: "סולם ברור",
    doesNotCountWhenHe: "מפה ללא סולם כשלא נלמד",
    rootsHe: ["קריאת סולם"],
    competitorsHe: ["זיכרון שם"],
    doNotConcludeHe: ["אין גאוגרפיה"],
    probeHe: "עם/בלי סולם מודגש",
    interventionHe: "סרגל + יחידות",
    escalationHe: "דיווח ראייה",
  },
  {
    id: "MG-02",
    subjectId: "moledet-geography",
    domainHe: "גאוגרפיה",
    topicHe: "כיוון",
    subskillHe: "צפון מוחלט",
    patternHe: "בלבול כשהמפה מוטה",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות כשיש חץ צפון"],
    counterEvidenceHe: "נכון כשצפון למעלה",
    countsWhenHe: "חץ צפון קיים",
    doesNotCountWhenHe: "בלי חץ כשלא נלמד",
    rootsHe: ["ייחוס מרחבי"],
    competitorsHe: ["רשלנות"],
    doNotConcludeHe: ["אין כיוון"],
    probeHe: "מפה מוטה מול ישרה",
    interventionHe: "סיבוב מפה",
    escalationHe: "אין שיפור",
  },
  {
    id: "MG-03",
    subjectId: "moledet-geography",
    domainHe: "מולדת",
    topicHe: "אזרחות",
    subskillHe: "זכות/חובה",
    patternHe: "מיון שגוי חוזר",
    minWrong: 4,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בזוגות שונים"],
    counterEvidenceHe: "נכון אחרי טבלה דועמודית",
    countsWhenHe: "טבלה זמינה",
    doesNotCountWhenHe: "טקסט משפטי שלא נלמד",
    rootsHe: ["מסגרת חוקית"],
    competitorsHe: ["זיכרון"],
    doNotConcludeHe: ["ערכים"],
    probeHe: "שני תרחישים",
    interventionHe: "מיון לטבלה",
    escalationHe: "מורה חברתי",
  },
  {
    id: "MG-04",
    subjectId: "moledet-geography",
    domainHe: "היסטוריה מקומית",
    topicHe: "ציר",
    subskillHe: "סדר אירועים",
    patternHe: "סדר הפוך",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בשני צירים"],
    counterEvidenceHe: "נכון עם תאריכים מודפסים",
    countsWhenHe: "כרטיסיות אירוע",
    doesNotCountWhenHe: "יותר מ 6 נקודות לפני שלב",
    rootsHe: ["ציר זמן"],
    competitorsHe: ["שמות דומים"],
    doNotConcludeHe: ["אין היסטוריה"],
    probeHe: "עם/בלי תאריכים",
    interventionHe: "ציר פיזי + כרטיסיות",
    escalationHe: "אין שיפור",
  },
  {
    id: "MG-05",
    subjectId: "moledet-geography",
    domainHe: "גאוגרפיה",
    topicHe: "אקלים",
    subskillHe: "מפת אקלים",
    patternHe: "אזור שגוי חוזר",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות כשיש מפתח"],
    counterEvidenceHe: "נכון עם מפתח",
    countsWhenHe: "מפתח זמין",
    doesNotCountWhenHe: "בלי מפתח כשלא נלמד",
    rootsHe: ["קריאת מפתח"],
    competitorsHe: ["זיכרון"],
    doNotConcludeHe: ["אין הבנה"],
    probeHe: "עם/בלי מפתח",
    interventionHe: "תרגול מפתח",
    escalationHe: "כישלון תמיד",
  },
  {
    id: "MG-06",
    subjectId: "moledet-geography",
    domainHe: "גאוגרפיה",
    topicHe: "אוכלוסין",
    subskillHe: "סיבהתוצאה",
    patternHe: "סיבה שגויה חוזרת",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות כשיש טקסט הסבר"],
    counterEvidenceHe: "נכון ברשימה סגורה",
    countsWhenHe: "טקסט הסבר קצר",
    doesNotCountWhenHe: "רק שמות",
    rootsHe: ["הסקה"],
    competitorsHe: ["זיכרון"],
    doNotConcludeHe: ["דעות קדומות"],
    probeHe: "שני הסברים מנוגדים",
    interventionHe: "שאלת מאין ידוע",
    escalationHe: "מורה חברתי",
  },
  {
    id: "MG-07",
    subjectId: "moledet-geography",
    domainHe: "מולדת",
    topicHe: "מוסדות",
    subskillHe: "תפקיד מוסד",
    patternHe: "בלבול תפקידים",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות חוזרת בין מוסדות"],
    counterEvidenceHe: "נכון ברשימה",
    countsWhenHe: "רשימה נלמדת",
    doesNotCountWhenHe: "מוסדות שלא נלמדו",
    rootsHe: ["מבנה ידע"],
    competitorsHe: ["שמות"],
    doNotConcludeHe: ["בעיה חברתית"],
    probeHe: "התאמת תפקיד למוסד",
    interventionHe: "טבלת מוסד–תפקיד",
    escalationHe: "אין שיפור",
  },
  {
    id: "MG-08",
    subjectId: "moledet-geography",
    domainHe: "גאוגרפיה",
    topicHe: "נוף",
    subskillHe: "סימבולים",
    patternHe: "סימול שגוי חוזר",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["אותו סימול"],
    counterEvidenceHe: "נכון במפתח",
    countsWhenHe: "מפתח זמין",
    doesNotCountWhenHe: "בלי מפתח",
    rootsHe: ["קריאת סימבול"],
    competitorsHe: ["זיכרון"],
    doNotConcludeHe: ["אין גאוגרפיה"],
    probeHe: "עם/בלי מפתח",
    interventionHe: "סימבולים בקבוצות קטנות",
    escalationHe: "אין שיפור",
  },
];
