/** @type {import("./taxonomy-types.js").TaxonomyRow[]} */
export const SCIENCE_TAXONOMY_ROWS = [
  {
    id: "S-01",
    subjectId: "science",
    domainHe: "מושג",
    topicHe: "סיווג",
    subskillHe: "תכונה מול תהליך",
    patternHe: "מיון לפי קטגוריה לא מתאימה",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בשני מושגים דומים"],
    counterEvidenceHe: "נכון אחרי טבלת דוגמאות",
    countsWhenHe: "טבלה מודרכת",
    doesNotCountWhenHe: "מסיחים הומופוניים בלבד",
    rootsHe: ["בלבול מושגי"],
    competitorsHe: ["קריאה"],
    doNotConcludeHe: ["אין מדעים"],
    probeHe: "הפרדה בין תכונה לבין תהליך (תרגול ממוקד)",
    interventionHe: "טבלת תכונה/תהליך",
    escalationHe: "אין שיפור",
  },
  {
    id: "S-02",
    subjectId: "science",
    domainHe: "שיטה",
    topicHe: "ניסוי",
    subskillHe: "משתנה מבודד",
    patternHe: "שינוי של יותר ממשתנה אחד בניסוי",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בתרחישי שינוי אחד"],
    counterEvidenceHe: "נכון עם טבלת משתנים",
    countsWhenHe: "טבלה זמינה",
    doesNotCountWhenHe: "טקסט ארוך בלי טבלה",
    rootsHe: ["הבנת ניסוי"],
    competitorsHe: ["זיכרון"],
    doNotConcludeHe: ["אין חשיבה"],
    probeHe: "אותו ניסוי עם טבלה",
    interventionHe: "משתנה אחד",
    escalationHe: "כישלון חוזר",
  },
  {
    id: "S-03",
    subjectId: "science",
    domainHe: "גוף",
    topicHe: "מערכות",
    subskillHe: "מיקום/זרימה",
    patternHe: "סדר או מיקום לא נכון במערכת",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות במפת גוף פשוטה"],
    counterEvidenceHe: "נכון עם מספור",
    countsWhenHe: "דיאגרמה ממוספרת",
    doesNotCountWhenHe: "שמות לטיניים שלא נלמדו",
    rootsHe: ["מפת מרחב גסה"],
    competitorsHe: ["שפה"],
    doNotConcludeHe: ["בעיה רפואית"],
    probeHe: "אנכי מול אופקי",
    interventionHe: "כרטיסיות מיקום",
    escalationHe: "דיווח רפואי",
  },
  {
    id: "S-04",
    subjectId: "science",
    domainHe: "חומר",
    topicHe: "מצבי צבירה",
    subskillHe: "שימור מסה",
    patternHe: "קושי בהבנת שימור החומר",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות כשיש דיאגרמת מצבים"],
    counterEvidenceHe: "נכון אחרי דיאגרמה",
    countsWhenHe: "דיאגרמה זמינה",
    doesNotCountWhenHe: "מילה בלי לימוד מצבים",
    rootsHe: ["שימור מסה"],
    competitorsHe: ["שפה"],
    doNotConcludeHe: ["אין פיזיקה"],
    probeHe: "עם/בלי דיאגרמה",
    interventionHe: "דיאגרמת מצבים",
    escalationHe: "אין שיפור",
  },
  {
    id: "S-05",
    subjectId: "science",
    domainHe: "אנרגיה",
    topicHe: "יחידות",
    subskillHe: "המרת יחידות",
    patternHe: "בלבול בין יחידות מידה",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות באותה יחידה"],
    counterEvidenceHe: "נכון עם מפתח",
    countsWhenHe: "מפתח זמין",
    doesNotCountWhenHe: "לפני לימוד יחידה",
    rootsHe: ["יחידות"],
    competitorsHe: ["חישוב"],
    doNotConcludeHe: ["אין הבנה"],
    probeHe: "שתי יחידות לאותו סכום",
    interventionHe: "מפתח יחידה",
    escalationHe: "כישלון תמיד",
  },
  {
    id: "S-06",
    subjectId: "science",
    domainHe: "מדידה",
    topicHe: "גרף",
    subskillHe: "קריאת ציר",
    patternHe: "קריאה לא נכונה של ערך מתוך גרף",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות בשני גרפים"],
    counterEvidenceHe: "נכון כשהציר מודגש",
    countsWhenHe: "צירים מתומחרים",
    doesNotCountWhenHe: "גרף לא מתומחר",
    rootsHe: ["קריאת גרף"],
    competitorsHe: ["חישוב"],
    doNotConcludeHe: ["אין מדעים"],
    probeHe: "עם/בלי הדגשת נקודה",
    interventionHe: "תרגול נקודה על ציר",
    escalationHe: "דיווח ראייה",
  },
  {
    id: "S-07",
    subjectId: "science",
    domainHe: "אקולוגיה",
    topicHe: "יחסים",
    // docs/audits/DECISION-ENGINE-CLAUDE-BLOCKER-CLOSURE-2026-07-24.md (Part 6):
    // required tags (environment_error, ecosystem_confusion — see
    // taxonomy-evidence-rules.js) only appear on genuine ecosystem-concept
    // questions (e.g. data/science-questions.js "env_2": "what is an
    // ecosystem?"). Recycling/conservation questions in the same
    // "environment" topic (e.g. "env_1") carry no such tag and structurally
    // cannot match this rule. Label broadened from the narrower "food web"
    // to the accurate scope of what can actually trigger this row.
    subskillHe: "מערכת אקולוגית ויחסים בין יצורים",
    patternHe: "בלבול בין רמות במערכת אקולוגית",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["טעות כשיש דיאגרמה"],
    counterEvidenceHe: "נכון ברשימה סגורה",
    countsWhenHe: "דיאגרמה או רשימה",
    doesNotCountWhenHe: "טקסט בלבד בלי לימוד",
    rootsHe: ["מבנה מערכת"],
    competitorsHe: ["זיכרון שמות"],
    doNotConcludeHe: ["אין מערכות"],
    probeHe: "רשת חלקית",
    interventionHe: "כרטיסיות",
    escalationHe: "אין שיפור",
  },
  {
    id: "S-08",
    subjectId: "science",
    domainHe: "בטיחות מדע",
    topicHe: "היגיון",
    subskillHe: "מקור לטענה",
    patternHe: "טענה שאינה נתמכת בראיה",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["חוזר כשיש מקור מפורש"],
    counterEvidenceHe: "נכון כשמבקשים מקור",
    countsWhenHe: "מקורות מסומנים",
    doesNotCountWhenHe: "מסיח פרסומת",
    rootsHe: ["ביקורתיות"],
    competitorsHe: ["קריאה"],
    doNotConcludeHe: ["ערכים אישיים"],
    probeHe: "עם/בלי מקור",
    interventionHe: "שאלת מאין ידוע",
    escalationHe: "מורה חברתי",
  },
];
