/**
 * Hebrew UI strings for parent worksheets module.
 * @module lib/worksheets/worksheet-ui.he
 */

export const WORKSHEET_UI_HE = {
  hubTitle: "דפי עבודה להדפסה",
  hubSubtitle:
    "בחרו דף מוכן, צרו דף אישי, או קבלו המלצה לפי התרגול של הילד — להדפסה נוחה בבית.",
  hubIntro:
    "כל דף עבודה נפתח בתצוגה מקדימה לפני ההדפסה. דף תשובות נוצר רק אם ביקשתם אותו במפורש.",
  tabReady: "דפים מוכנים",
  tabGenerator: "יצירת דף עבודה",
  tabRecommendations: "המלצות לילד שלי",
  print: "הדפסה",
  preview: "תצוגה מקדימה",
  answerKey: "דף תשובות",
  answerKeySeparate: "דף תשובות נפרד — נוצר רק בבקשה מפורשת",
  inkSave: "חסכון בדיו",
  noAnswersInWorksheet: "ללא תשובות בדף העבודה",
  subjectMath: "מתמטיקה / חשבון",
  subjectGeometry: "גיאומטריה",
  subjectHebrew: "עברית",
  subjectEnglish: "אנגלית",
  blockedAudio: "שאלה זו דורשת שמע ואינה ניתנת להדפסה",
  blockedImage: "שאלה זו דורשת תמונה ואינה ניתנת להדפסה",
  questionLabel: "שאלה",
  nameField: "שם",
  dateField: "תאריך",
  gradeField: "כיתה",
  topicField: "נושא",
  practiceFormatField: "סוג תרגול",
  levelField: "רמה",
  countField: "כמות שאלות",
  includeAnswers: "כולל דף תשובות",
  createWorksheet: "צור דף עבודה",
  viewAndPrint: "צפה והדפס",
  back: "חזרה",
  loading: "טוען…",
  errorGeneric: "משהו השתבש. נסו שוב.",
  noStudents: "אין ילדים מקושרים לחשבון.",
  selectChild: "בחרו ילד",
  recommendationsEmpty: "אחרי עוד קצת תרגול נוכל להציע דפי עבודה מותאמים לילד.",
  recommendationsEmptyTitle: "עדיין אין המלצות",
  recommendationsTitle: "המלצות לפי תרגול",
  recommendationsHint: "המלצות מבוססות על נושאים שהילד תרגל לאחרונה — לא על דוח ההורים.",
  readyTitle: "דפי עבודה מוכנים",
  readyHint: "30 דפים מוכנים · 12 שאלות בכל דף (2 עמודי הדפסה) — לחצו צפה והדפס לבדיקה לפני ההדפסה.",
  readyEmptyTitle: "לא נמצאו דפים",
  readyEmptyText: "נסו לשנות את הסינון — או בחרו את כל המקצועות, הכיתות והרמות.",
  createTitle: "יצירת דף עבודה חדש",
  createHint: "בחרו מקצוע, כיתה, נושא ורמה — ואז צרו דף מותאם להדפסה.",
  previewTitle: "תצוגה מקדימה",
  documentTitle: "דף עבודה",
  answerKeyTitle: "דף תשובות",
  noPreviewData: "אין דף עבודה לתצוגה. חזרו ליצירת דף.",
  generating: "יוצר דף עבודה…",
  refreshQuestions: "רענן שאלות",
  refreshingQuestions: "מייצרים שאלות חדשות…",
  refreshQuestionsError: "לא הצלחנו ליצור שאלות חדשות. נסו שוב.",
  questionCount: "שאלות",
  createFromRecommendation: "צור דף מהמלצה",
};
