/**
 * Hebrew UI strings for parent worksheets module.
 * @module lib/worksheets/worksheet-ui.he
 */

export const WORKSHEET_UI_HE = {
  hubTitle: "דפי עבודה להדפסה",
  hubSubtitle:
    "בחרו דף מוכן, צרו דף אישי, או קבלו דפים מומלצים מהמערכת על סמך התרגול של הילד שלכם.",
  hubIntro:
    "כל דף עבודה נפתח בתצוגה מקדימה לפני ההדפסה. דף תשובות אופציונלי לנוחיותכם.",
  tabReady: "דף מוכן",
  tabGenerator: "יצירת חדש",
  tabRecommendations: "המלצת המערכת",
  print: "הדפסה",
  preview: "תצוגה מקדימה",
  answerKey: "דף תשובות",
  answerKeySeparate: "דף תשובות נפרד - נוצר רק בבקשה מפורשת",
  inkSave: "חסכון בדיו",
  noAnswersInWorksheet: "ללא תשובות בדף העבודה",
  subjectMath: "מתמטיקה",
  subjectGeometry: "גאומטריה",
  subjectHebrew: "עברית",
  subjectEnglish: "אנגלית",
  blockedAudio: "שאלה זו דורשת שמע ואינה ניתנת להדפסה",
  blockedImage: "שאלה זו דורשת תמונה ואינה ניתנת להדפסה",
  questionLabel: "שאלה",
  nameField: "שם",
  dateField: "תאריך",
  gradeField: "כיתה",
  topicField: "נושא",
  practiceFormatField: "סוג תרגול",
  levelField: "רמה",
  countField: "כמות שאלות",
  includeAnswers: "כולל דף תשובות",
  preferMcq: "שאלות אמריקאיות",
  preferMcqHint: "אם קיים במאגר - יוצגו אפשרויות בחירה",
  preferMcqUnavailable: "בנושא זה אין שאלות אמריקאיות זמינות",
  createWorksheet: "צור דף עבודה",
  viewAndPrint: "צפה והדפס",
  back: "חזרה",
  loading: "טוען…",
  errorGeneric: "משהו השתבש. נסו שוב.",
  noStudents: "אין ילדים מקושרים לחשבון.",
  selectChild: "בחרו ילד",
  recommendationsEmpty: "אחרי עוד קצת תרגול נוכל להציע דפי עבודה מותאמים לילד.",
  recommendationsEmptyTitle: "עדיין אין המלצות",
  recommendationsTitle: "המלצות לפי תרגול",
  recommendationsHint: "המלצות מבוססות על נושאים שהילד תרגל לאחרונה - לא על דוח ההורים.",
  readyTitle: "דפי עבודה מוכנים",
  readyHint: "30 דפים מוכנים · 12 שאלות בכל דף.",
  readyEmptyTitle: "לא נמצאו דפים",
  readyEmptyText: "נסו לשנות את הסינון - או בחרו את כל המקצועות, הכיתות והרמות.",
  createTitle: "יצירת דף עבודה חדש",
  createHint: "בחרו מקצוע, כיתה, נושא ורמה - ואז צרו דף מותאם להדפסה.",
  mixedTopicsTitle: "בחירת נושאים תרגול מעורב",
  mixedTopicsHint: "סמנו את הנושאים שייכללו בתרגול המעורב. כברירת מחדל כל הנושאים מסומנים.",
  mixedTopicsSelectAll: "בחר את כל הנושאים",
  mixedTopicsEmptyError: "יש לבחור לפחות נושא אחד לתרגול.",
  previewTitle: "תצוגה מקדימה",
  documentTitle: "דף עבודה",
  answerKeyTitle: "דף תשובות",
  noPreviewData: "אין דף עבודה לתצוגה. חזרו ליצירת דף.",
  generating: "יוצר דף עבודה…",
  refreshQuestions: "רענן שאלות",
  refreshingQuestions: "מייצרים שאלות חדשות…",
  refreshQuestionsError: "לא הצלחנו ליצור שאלות חדשות. נסו שוב.",
  answerKeyStale:
    "דף התשובות עודכן לפי השאלות הנוכחיות. נסו לפתוח שוב את דף התשובות.",
  questionCount: "שאלות",
  createFromRecommendation: "צור דף מהמלצה",
  publicDemoTitle: "נסו את מחולל דפי העבודה",
  publicDemoHint: "דף התנסות קצר עם 8 תרגילים - בחרו מקצוע, כיתה ונושא.",
  publicDemoCreate: "יצירת דף התנסות",
  publicDemoLockedTopic: "נושאים נוספים זמינים במערכת המלאה להורים",
  publicReadyTitle: "דפי עבודה מוכנים לפי כיתה",
  publicReadyHint: "35 דפי עבודה מוכנים - סננו, צפו, הדפיסו ובדקו עם דף תשובות.",
  publicPreviewLost:
    "נתוני התצוגה אינם זמינים. חזרו לעמוד דפי העבודה ובחרו שוב דף להצגה.",
  publicPreviewLostCta: "חזרה לדפי עבודה",
  worksheetTypeQuestions: "דפי שאלות",
  worksheetTypeWriting: "דפי כתיבה",
  worksheetTypeAll: "כל הסוגים",
  writingCategoryField: "קטגוריית כתיבה",
  writingCategoryAll: "כל הקטגוריות",
  writingCreateTitle: "יצירת דף תרגול כתיבה",
  writingCreateHint: "בחרו קטגוריה, סוג תרגול ומספר שורות — ואז צרו דף מותאם להדפסה.",
  writingCreateWorksheet: "צור דף כתיבה",
  writingDocumentTitle: "דף תרגול כתיבה",
  writingPublicDemoTitle: "נסו את מחולל דפי הכתיבה",
  writingPublicDemoHint: "דף התנסות קצר — בחרו תבנית מוכנה וצרו דף לדוגמה.",
  writingPublicDemoCreate: "יצירת דף כתיבה לדוגמה",
  writingDemoPresetField: "תבנית התנסות",
  writingLettersField: "אותיות",
  writingLetterCaseField: "סוג אות",
  writingNumberModeField: "סוג תרגול מספרים",
  writingPrewritingField: "סוג קו",
  writingWordPackField: "חבילת מילים",
  writingCustomWordsField: "מילים מותאמות",
  writingPersonalKindField: "סוג טקסט",
  writingPersonalTextField: "טקסט",
  writingTracingField: "סוג תרגול",
  writingScriptField: "סגנון כתב",
  writingLineCountField: "מספר שורות",
  writingOrientationField: "כיוון דף",
  writingLineCount: "שורות",
  writingLockedTitle: "דף זה זמין במערכת המלאה",
  writingLockedText:
    "דף תרגול כתיבה זה זמין להורים במערכת LEO KIDS. הירשמו או התחברו כדי לגשת לכל 270 דפי הכתיבה.",
  writingLockedClose: "הבנתי",
  writingSearchPlaceholder: "חיפוש לפי שם או מספר…",
  writingCatalogHint: "305 דפים · 35 שאלות + 270 כתיבה",
  writingReadyHint: "דפי כתיבה מוכנים — 25 דוגמאות ציבוריות, 245 נוספים במערכת המלאה.",
  tabWritingGenerator: "מחולל כתיבה",
  createTypeQuestions: "דפי שאלות",
  createTypeWriting: "דפי כתיבה",
  createTypeColoring: "דפי צביעה",
  coloringCreateTitle: "דפי צביעה",
  coloringCreateHint: 'בחרו תמונה, לחצו על "פתחו והדפיסו" - ייפתח דף A4 בתצוגה מקדימה.',
  coloringCreateHintSub: "ניתן להדפיס ישירות מהחלון שנפתח, או לסגור ולבחור קלף אחר.",
  coloringCreateWorksheet: "פתחו והדפיסו",
  coloringModalClose: "סגירה",
  coloringSearchPlaceholder: "חיפוש לפי שם קלף…",
  coloringCategoryField: "סוג קלף",
  coloringCategoryAll: "כל הסוגים",
  coloringEmpty: "לא נמצאו דפי צביעה.",
  coloringCardListLabel: "רשימת קלפים לצביעה",
  coloringSelectedLabel: "נבחר",
  coloringDocumentTitle: "דף צביעה",
};
