/**
 * Hebrew UI strings for parent worksheets module.
 * @module lib/worksheets/worksheet-ui.he
 */

export const WORKSHEET_UI_HE = {
  hubTitle: "דפי עבודה להדפסה",
  hubSubtitle:
    "בחרו דף מוכן, צרו דף אישי, או קבלו דפים מומלצים מהמערכת על סמך התרגול של הילד שלכם.",
  hubIntro:
    "כל דף עבודה נפתח בתצוגה מקדימה לפני ההדפסה. דף תשובות אופציונלי לנוחיותכם.",
  tabReady: "דף מוכן",
  tabGenerator: "יצירת חדש",
  tabRecommendations: "המלצת המערכת",
  print: "הדפסה",
  preview: "תצוגה מקדימה",
  answerKey: "דף תשובות",
  answerKeySeparate: "דף תשובות נפרד - נוצר רק בבקשה מפורשת",
  inkSave: "חסכון בדיו",
  noAnswersInWorksheet: "ללא תשובות בדף העבודה",
  subjectMath: "מתמטיקה",
  subjectGeometry: "גאומטריה",
  subjectHebrew: "עברית",
  subjectEnglish: "אנגלית",
  blockedAudio: "שאלה זו דורשת שמע ואינה ניתנת להדפסה",
  blockedImage: "שאלה זו דורשת תמונה ואינה ניתנת להדפסה",
  questionLabel: "שאלה",
  nameField: "שם",
  dateField: "תאריך",
  gradeField: "כיתה",
  topicField: "נושא",
  practiceFormatField: "סוג תרגול",
  levelField: "רמה",
  countField: "כמות שאלות",
  includeAnswers: "כולל דף תשובות",
  preferMcq: "שאלות אמריקאיות",
  preferMcqHint: "אם קיים במאגר - יוצגו אפשרויות בחירה",
  preferMcqUnavailable: "בנושא זה אין שאלות אמריקאיות זמינות",
  createWorksheet: "צור דף עבודה",
  viewAndPrint: "צפה והדפס",
  back: "חזרה",
  loading: "טוען…",
  errorGeneric: "משהו השתבש. נסו שוב.",
  noStudents: "אין ילדים מקושרים לחשבון.",
  selectChild: "בחרו ילד",
  recommendationsEmpty: "אחרי עוד קצת תרגול נוכל להציע דפי עבודה מותאמים לילד.",
  recommendationsEmptyTitle: "עדיין אין המלצות",
  recommendationsTitle: "המלצות לפי תרגול",
  recommendationsHint: "המלצות מבוססות על נושאים שהילד תרגל לאחרונה - לא על דוח ההורים.",
  readyTitle: "דפי עבודה מוכנים",
  readyHint: "30 דפים מוכנים · 12 שאלות בכל דף.",
  readyEmptyTitle: "לא נמצאו דפים",
  readyEmptyText: "נסו לשנות את הסינון - או בחרו את כל המקצועות, הכיתות והרמות.",
  createTitle: "יצירת דף עבודה חדש",
  createHint: "בחרו מקצוע, כיתה, נושא ורמה - ואז צרו דף מותאם להדפסה.",
  mixedTopicsTitle: "בחירת נושאים תרגול מעורב",
  mixedTopicsHint: "סמנו את הנושאים שייכללו בתרגול המעורב. כברירת מחדל כל הנושאים מסומנים.",
  mixedTopicsSelectAll: "בחר את כל הנושאים",
  mixedTopicsEmptyError: "יש לבחור לפחות נושא אחד לתרגול.",
  previewTitle: "תצוגה מקדימה",
  documentTitle: "דף עבודה",
  answerKeyTitle: "דף תשובות",
  noPreviewData: "אין דף עבודה לתצוגה. חזרו ליצירת דף.",
  generating: "יוצר דף עבודה…",
  refreshQuestions: "רענן שאלות",
  refreshingQuestions: "מייצרים שאלות חדשות…",
  refreshQuestionsError: "לא הצלחנו ליצור שאלות חדשות. נסו שוב.",
  answerKeyStale:
    "דף התשובות עודכן לפי השאלות הנוכחיות. נסו לפתוח שוב את דף התשובות.",
  questionCount: "שאלות",
  createFromRecommendation: "צור דף מהמלצה",
  publicDemoTitle: "נסו את מחולל דפי העבודה",
  publicDemoHint: "דף התנסות קצר עם 8 תרגילים - בחרו מקצוע, כיתה ונושא.",
  publicDemoCreate: "יצירת דף התנסות",
  publicDemoLockedTopic: "נושאים נוספים זמינים במערכת המלאה להורים",
  publicReadyTitle: "דפי עבודה מוכנים לפי כיתה",
  publicReadyHint: "35 דפי עבודה מוכנים - סננו, צפו, הדפיסו ובדקו עם דף תשובות.",
  publicPreviewLost:
    "נתוני התצוגה אינם זמינים. חזרו לעמוד דפי העבודה ובחרו שוב דף להצגה.",
  publicPreviewLostCta: "חזרה לדפי עבודה",
  worksheetTypeQuestions: "דפי שאלות",
  worksheetTypeWriting: "דפי כתיבה",
  worksheetTypeAll: "כל הסוגים",
  writingCategoryField: "קטגוריית כתיבה",
  writingCategoryAll: "כל הקטגוריות",
  writingCreateTitle: "יצירת דף תרגול כתיבה",
  writingCreateHint: "בחרו קטגוריה, סוג תרגול ומספר שורות — ואז צרו דף מותאם להדפסה.",
  writingCreateWorksheet: "צור דף כתיבה",
  writingDocumentTitle: "דף תרגול כתיבה",
  writingPublicDemoTitle: "נסו את מחולל דפי הכתיבה",
  writingPublicDemoHint: "דף התנסות קצר — בחרו תבנית מוכנה וצרו דף לדוגמה.",
  writingPublicDemoCreate: "יצירת דף כתיבה לדוגמה",
  writingDemoPresetField: "תבנית התנסות",
  writingLettersField: "אותיות",
  writingLetterCaseField: "סוג אות",
  writingNumberModeField: "סוג תרגול מספרים",
  writingPrewritingField: "סוג קו",
  writingWordPackField: "חבילת מילים",
  writingCustomWordsField: "מילים מותאמות",
  writingPersonalKindField: "סוג טקסט",
  writingPersonalTextField: "טקסט",
  writingTracingField: "סוג תרגול",
  writingScriptField: "סגנון כתב",
  writingLineCountField: "מספר שורות",
  writingOrientationField: "כיוון דף",
  writingLineCount: "שורות",
  writingLockedTitle: "דף זה זמין במערכת המלאה",
  writingLockedText:
    "דף תרגול כתיבה זה זמין להורים במערכת LEO KIDS. הירשמו או התחברו כדי לגשת לכל 270 דפי הכתיבה.",
  writingLockedClose: "הבנתי",
  writingSearchPlaceholder: "חיפוש לפי שם או מספר…",
  writingCatalogHint: "305 דפים · 35 שאלות + 270 כתיבה",
  writingReadyHint: "דפי כתיבה מוכנים — 25 דוגמאות ציבוריות, 245 נוספים במערכת המלאה.",
  tabWritingGenerator: "מחולל כתיבה",
  createTypeQuestions: "דפי שאלות",
  createTypeWriting: "דפי כתיבה",
  createTypeColoring: "דפי צביעה",
  coloringCreateTitle: "דפי צביעה",
  coloringCreateHint: 'בחרו תמונה, לחצו על "פתחו והדפיסו" - ייפתח דף A4 בתצוגה מקדימה.',
  coloringCreateHintSub: "ניתן להדפיס ישירות מהחלון שנפתח, או לסגור ולבחור קלף אחר.",
  coloringCreateWorksheet: "פתחו והדפיסו",
  coloringModalClose: "סגירה",
  coloringSearchPlaceholder: "חיפוש לפי שם קלף…",
  coloringCategoryField: "סוג קלף",
  coloringCategoryAll: "כל הסוגים",
  coloringEmpty: "לא נמצאו דפי צביעה.",
  coloringCardListLabel: "רשימת קלפים לצביעה",
  coloringSelectedLabel: "נבחר",
  coloringDocumentTitle: "דף צביעה",
  coloringUploadModeCards: "דפי צביעה מהקלפים",
  coloringUploadModeUpload: "יצירה מתמונה שלי",
  coloringUploadBadge: "חדש",
  coloringUploadTitle: "יצירת דף צביעה מתמונה",
  coloringUploadHint:
    "התמונה שתעלו נשלחת באופן מאובטח לשירות עיבוד חיצוני לצורך יצירת דף הצביעה בלבד. היא אינה נשמרת במערכות LEO KIDS.",
  coloringUploadTechNote:
    "המערכת משתמשת בבינה מלאכותית כדי ליצור דף צביעה נקי וברור.",
  coloringUploadPrivacyTitle: "הפרטיות שלכם חשובה",
  coloringUploadPrivacyBody:
    "התמונה שתעלו נשלחת באופן מאובטח לשירות עיבוד חיצוני לצורך יצירת דף הצביעה בלבד. היא אינה נשמרת במערכות LEO KIDS.",
  coloringUploadPrivacyAccept: "הבנתי, המשך",
  coloringUploadDropzone: "גררו תמונה לכאן או לחצו לבחירה",
  coloringUploadDropzoneOverlay: "שחררו את התמונה להעלאה",
  coloringUploadChooseFile: "בחירת קובץ",
  coloringUploadCamera: "צילום מהמצלמה",
  coloringUploadCropTitle: "חתכו ויישרו את התמונה",
  coloringUploadRotate: "סיבוב",
  coloringUploadAspectAuto: "אוטומטי",
  coloringUploadAspectA4: "A4 אנכי",
  coloringUploadZoom: "זום",
  coloringUploadCropConfirm: "יצירת דף צביעה",
  coloringUploadCropPreviewLabel: "תמונה שתעובד",
  coloringUploadPresetLegend: "מצב עיבוד",
  coloringUploadPresetSimple: "קל לילדים",
  coloringUploadPresetBalanced: "מאוזן",
  coloringUploadPresetDetailed: "מפורט",
  coloringUploadProcessing: "מעבדים… אל תעזבו את הדף",
  coloringUploadStayOnPage: "אל תעזבו את הדף בזמן העיבוד.",
  coloringUploadCancel: "ביטול",
  coloringUploadAdjustThickness: "עובי קווים",
  coloringUploadAdjustDetail: "כמות פרטים",
  coloringUploadAdjustBg: "ניקוי רקע",
  coloringUploadAdjustBrightness: "בהירות",
  coloringUploadAdjustContrast: "ניגודיות",
  coloringUploadReprocess: "עיבוד מחדש (אחרי חיתוך)",
  coloringUploadManualTitle: "תיקון ידני",
  coloringUploadBrushWhite: "מחק (לבן)",
  coloringUploadBrushBlack: "קו (שחור)",
  coloringUploadBrushSize: "גודל מברשת",
  coloringUploadUndo: "ביטול",
  coloringUploadRedo: "שחזור",
  coloringUploadPreviewAlt: "תצוגה מקדימה של דף הצביעה",
  coloringUploadShowBefore: "לפני / אחרי — מקור",
  coloringUploadShowAfter: "לפני / אחרי — תוצאה",
  coloringUploadTitleField: "כותרת (אופציונלי — ברירת מחדל ללא כותרת)",
  coloringUploadTitlePlaceholder: "השאירו ריק ללא כותרת",
  coloringUploadPrint: "הדפסה",
  coloringUploadDownload: "הורדת PNG",
  coloringUploadRestart: "התחלה מחדש",
  coloringUploadBackToCards: "חזרה לקלפים",
  coloringUploadUnsupported: "הדפדפן שלך לא תומך בכלי זה. נסו Chrome, Edge או Safari עדכני.",
  coloringUploadWeakDevice: "מכשיר זה עלול לעבד לאט — מומלץ תמונה קטנה יותר.",
  coloringUploadHeicFailed: "לא הצלחנו לפתוח את התמונה. שמרו כ-JPG מהגלריה.",
  coloringUploadLoadFailed: "לא הצלחנו לטעון את התמונה.",
  coloringUploadProcessFailed: "העיבוד נכשל. נסו שוב.",
  coloringUploadBadResult: "לא הצלחנו ליצור דף צביעה טוב. נסו תמונה עם רקע פשוט יותר.",
  coloringUploadEngineFailed: "לא הצלחנו להפעיל את מנוע העיבוד. נסו לרענן את הדף.",
  coloringUploadPhaseWorkerStarted: "מפעילים את מנוע העיבוד…",
  coloringUploadPhaseOpenCvLoading: "טוענים את OpenCV…",
  coloringUploadPhaseOpenCvReady: "OpenCV מוכן — מתחילים עיבוד",
  coloringUploadPhaseSegment: "מפרידים את הנושא מהרקע…",
  coloringUploadPhaseHfLineart: "יוצרים קווי מתאר באמצעות AI…",
  coloringUploadPhaseHfFallback: "חוזרים לעיבוד מקומי (OpenCV)…",
  coloringUploadFallbackNotice:
    "שירות העיבוד הראשי אינו זמין כרגע. יוצרים את הדף בדרך חלופית.",
  coloringUploadQuotaRemaining: (remaining, limit) =>
    `נותרו לכם היום ${remaining} מתוך ${limit} יצירות.`,
  coloringUploadQuotaUser:
    "הגעתם למגבלת 10 דפי הצביעה היומית. תוכלו ליצור דפים נוספים מחר.",
  coloringUploadQuotaGlobal: "מכסת היצירות היומית באתר הסתיימה. נסו שוב מחר.",
  coloringUploadPayloadTooLarge:
    "התמונה גדולה מדי לעיבוד. נסו תמונה אחרת או חיתוך קטן יותר.",
  coloringUploadStyleLegend: "בחרו סגנון יצירה",
  coloringUploadStyleColoringTitle: "דף צביעה",
  coloringUploadStyleComicTitle: "קומיקס",
  coloringUploadStylePencilTitle: "ציור עפרון",
  coloringUploadStyleAnimeTitle: "אנימה",
  coloringUploadStylePixarTitle: "תלת מימד",
  coloringUploadCreateColoring: "יצירת דף צביעה",
  coloringUploadCreateArt: "יצירת יצירת אמנות",
  coloringUploadPhaseStyleTransfer: "מעבדים את התמונה בסגנון שנבחר…",
  coloringUploadStyleTransferFailed: "לא הצלחנו ליצור את הסגנון שנבחר. נסו שוב.",
  coloringUploadStyleTransferTimeout: "העיבוד לקח יותר מדי זמן. נסו שוב.",
  coloringUploadStyleTransferUnavailable: "שירות הסגנונות אינו זמין כרגע. נסו שוב מאוחר יותר.",
  coloringUploadStyleTransferRateLimited: "שירות הסגנונות עמוס כרגע. נסו שוב בעוד מספר דקות.",
};
