-- NOT a migration. Run in Supabase SQL editor BEFORE applying 034_school_account_audit_actions.sql
-- Expected: zero rows. If any row appears, do NOT apply 034 until the allowlist is extended.

SELECT action, COUNT(*) AS n
FROM public.teacher_access_audit
WHERE action NOT IN (
  'grant_created',
  'grant_revoked',
  'grant_expired',
  'pin_rotated',
  'username_rotated',
  'magic_link_sent',
  'magic_link_consumed',
  'magic_link_expired',
  'guardian_login_success',
  'guardian_login_failed',
  'guardian_logout',
  'teacher_link_created',
  'teacher_link_archived',
  'teacher_onboarded',
  'class_created',
  'class_archived',
  'class_updated',
  'class_member_added',
  'class_member_removed',
  'viewed_student_report',
  'viewed_class_report',
  'link_created',
  'link_archived',
  'link_consent_failed',
  'link_limit_reached',
  'consent_issued',
  'consent_revoked',
  'magic_link_issued',
  'student_created_by_teacher',
  'student_name_updated',
  'activity_created',
  'activity_activated',
  'activity_paused',
  'activity_closed',
  'activity_archived',
  'school_subject_granted',
  'school_subject_revoked',
  'school_student_enrolled',
  'school_student_unenrolled',
  'school_class_viewed',
  'school_student_report_viewed',
  'school_student_class_transferred',
  'school_class_teacher_reassigned',
  'school_class_archived',
  'worksheet_activity_created',
  'worksheet_activity_activated',
  'worksheet_activity_closed',
  'worksheet_activity_archived',
  'worksheet_pdf_uploaded',
  'worksheet_result_published',
  'school_student_access_created',
  'school_student_access_revoked',
  'school_student_pin_rotated',
  'school_student_access_blocked',
  'school_student_access_unblocked',
  'school_parent_access_created',
  'school_parent_access_revoked',
  'school_parent_pin_rotated',
  'school_parent_access_blocked',
  'school_parent_access_unblocked',
  'school_parent_linked_to_student',
  'school_parent_unlinked_from_student',
  'school_parent_pin_changed_by_parent',
  'school_message_sent',
  'school_message_hidden',
  'school_message_read'
)
GROUP BY action
ORDER BY n DESC;

-- Optional: full distinct list for manual diff against migration 034
-- SELECT DISTINCT action FROM public.teacher_access_audit ORDER BY 1;
